name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  dio: ^5.8.0+1
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  geolocator: ^14.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  freezed: ^3.0.6


flutter:
  uses-material-design: true

  assets:
    - assets/img/
