// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/features/weather/data/repositories/weather/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:weather_app/app/environment/environment.dart' as _i3;
import 'package:weather_app/core/utils/result.dart' as _i6;
import 'package:weather_app/features/weather/data/services/weather/openweather_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnvironment_1 extends _i1.SmartFake implements _i3.Environment {
  _FakeEnvironment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OpenWeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenWeatherService extends _i1.Mock
    implements _i4.OpenWeatherService {
  MockOpenWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.Environment get environment =>
      (super.noSuchMethod(
            Invocation.getter(#environment),
            returnValue: _FakeEnvironment_1(
              this,
              Invocation.getter(#environment),
            ),
          )
          as _i3.Environment);

  @override
  _i5.Future<_i6.Result<Map<String, dynamic>>> getWeather(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeather, [lat, lon]),
            returnValue: _i5.Future<_i6.Result<Map<String, dynamic>>>.value(
              _i7.dummyValue<_i6.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getWeather, [lat, lon]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<Map<String, dynamic>>>);
}
